### ISSUE TITLE
Github-like markdown support

### ISSUE THREAD

**Issue by xeranas** [ButterFaces/ButterFaces#113]
Multiline code blocks for b:markdown readonly or preview output generates into singleline.

Having input:

> \```javascript
> var s = "JavaScript syntax highlighting";
> alert(s);
> \```
> 

I do expect:

> var s = "JavaScript syntax highlighting";
> alert(s);

But actual I get:
> javascript var s = "JavaScript syntax highlighting"; alert(s); 

it does even includes name of script language.

I solved markdown parsing issues by replacing build-in markdown.js parser with [showdown](https://github.com/showdownjs/showdown). Code formatting worked correctly out of the box. Additional showdown lib options like 'simpleLineBreaks', 'openLinksInNewWindow' helped to make markdown the way I liked.

**Comment by larmic** [comment]
I will take a look on it.

**Comment by larmic** [comment]
After a while.

ButterFaces 3.0 is coming soon and replaces javascript by markdown.

Stay tuned.
