### ISSUE TITLE
ButterFaces does not prepend the portlet namespace

### ISSUE THREAD

**Issue by ngriffin7a** [ButterFaces/ButterFaces#115]
The Liferay Faces team recently developed the [butterfaces-applicant-portlet](https://github.com/liferay/liferay-faces-bridge-impl/tree/4.x/demo/butterfaces-applicant-portlet) in order to investigate portlet support for ButterFaces.

During our investigation we found that ButterFaces was not prepending the portlet namespace to request parameters.

For example, given the following XHTML...
```
<b:text id="firstName" label="#{i18n['first-name']}" required="true"
	value="#{applicantModelBean.firstName}">
	<f:ajax event="blur" render="firstName" />
</b:text>
```
... then following HTML will be rendered:

```
<input id="_1_WAR_comliferayfacesdemobutterfacesapplicantportlet_INSTANCE_ABCD_:f1:firstName:inner" name="_1_WAR_comliferayfacesdemobutterfacesapplicantportlet_INSTANCE_ABCD_:f1:firstName" value="" onblur="jsf.ajax.request('_1_WAR_comliferayfacesdemobutterfacesapplicantportlet_INSTANCE_ABCD_:f1:firstName', 'blur', {render: '_1_WAR_comliferayfacesdemobutterfacesapplicantportlet_INSTANCE_ABCD_:f1:firstName', 'javax.faces.behavior.event': 'blur'});" class="butter-input-component form-control butter-component-invalid">
```

This causes jsf.ajax.request to submit the following request parameters:

```
javax.faces.source:_1_WAR_comliferayfacesdemobutterfacesapplicantportlet_INSTANCE_ABCD_:f1:firstName
javax.faces.partial.execute:_1_WAR_comliferayfacesdemobutterfacesapplicantportlet_INSTANCE_ABCD_:f1:firstName _1_WAR_comliferayfacesdemobutterfacesapplicantportlet_INSTANCE_ABCD_:f1:firstName
javax.faces.partial.render:_1_WAR_comliferayfacesdemobutterfacesapplicantportlet_INSTANCE_ABCD_:f1:firstName
javax.faces.behavior.event:blur
javax.faces.partial.ajax:true
```

But jsf.ajax.request should be submitting these parameters with the namespace prefix:

```
_1_WAR_comliferayfacesdemobutterfacesapplicantportlet_INSTANCE_ABCD_javax.faces.source:_1_WAR_comliferayfacesdemobutterfacesapplicantportlet_INSTANCE_ABCD_:f1:firstName
_1_WAR_comliferayfacesdemobutterfacesapplicantportlet_INSTANCE_ABCD_javax.faces.partial.execute:_1_WAR_comliferayfacesdemobutterfacesapplicantportlet_INSTANCE_ABCD_:f1:firstName _1_WAR_comliferayfacesdemobutterfacesapplicantportlet_INSTANCE_ABCD_:f1:firstName
javax.faces.partial.render:_1_WAR_comliferayfacesdemobutterfacesapplicantportlet_INSTANCE_ABCD_:f1:firstName
_1_WAR_comliferayfacesdemobutterfacesapplicantportlet_INSTANCE_ABCD_javax.faces.behavior.event:blur
_1_WAR_comliferayfacesdemobutterfacesapplicantportlet_INSTANCE_ABCD_javax.faces.partial.ajax:true
```

Specifically, we found that ButterFaces does not respect the following context parameter for Mojarra:
```
<context-param>
	<param-name>com.sun.faces.namespaceParameters</param-name>
	<param-value>false</param-value>
</context-param>
```

When this parameter is `true`, [Mojarra 2.2/2.1 will pass](https://github.com/javaserverfaces/mojarra/blob/MOJARRA_2_2X_ROLLING/jsf-ri/src/main/java/com/sun/faces/renderkit/html_basic/AjaxBehaviorRenderer.java#L260) 'com.sun.faces.namingContainerId' with the namespace prefix as an option to the [jsf.ajax.request JavaScript API](http://docs.oracle.com/cd/E17802_01/j2ee/javaee/javaserverfaces/2.0/docs/js-api/symbols/jsf.ajax.html#.request).

**Comment by larmic** [comment]
Hi,

ok, we have never used namespace parameters. I don't know if this feature only works on mojarra or myfaces as well.

We will check this.

**Comment by larmic** [comment]
@szerhusenBC do you know something about it?

**Comment by szerhusenBC** [comment]
@larmic Not yet. Have to check that as well ;)

**Comment by ngriffin7a** [comment]
The com.sun.faces.namespaceParameters context-param is a Mojarra 2.1/2.2 specific feature and therefore doesn't exist in MyFaces. However, it has been standardized in JSF 2.3 but in a slightly different way. Instead of specifying a context-param, Mojarra and MyFaces will *always* prepend the namespace prefix if `(uiViewRoot instanceof NamingContainer)` (which evaluates to `true` in a portlet environment because of [PortletNamingContainerUIViewRoot](https://github.com/liferay/liferay-faces-bridge-api/blob/master/bridge-api/src/main/java/javax/portlet/faces/component/PortletNamingContainerUIViewRoot.java). Note that in JSF 2.3 (Mojarra 2.3), that a [separator character is added after the namespace prefix](https://github.com/javaserverfaces/mojarra/blob/master/impl/src/main/java/com/sun/faces/renderkit/RenderKitUtils.java#L1479). The separator character syntax does not appear in Mojarra 2.2/2.1.

**Comment by szerhusenBC** [comment]
@ngriffin7a In a portal environment every portlet counts as a view tree root, right? We never worked in a portal environment before.

**Comment by ngriffin7a** [comment]
@szerhusenBC That's correct. One of the reasons why the FacesBridge API causes the ViewRoot to implement NamingContainer is to guarantee uniqueness of HTML id elements when more than one instance of the same JSF portlet is placed on the same page. If it would help, I could provide you with a link to a Pluto 2.0 Tomcat bundle that includes our butterfaces-applicant-portlet. That way you could see it in action.

**Comment by szerhusenBC** [comment]
@ngriffin7a that would be nice ;)

**Comment by ngriffin7a** [comment]
@szerhusenBC [Here](http://www.liferayfaces.org/downloads/butterfaces/pluto-2.0.3-jsf-2.2.zip) is a Pluto 2.0 Tomcat bundle that you can download and run. After you startup Tomcat, visit the following URL: http://localhost:9080/pluto/portal/butterfaces-applicant

Each of the text fields is Ajaxified. If you enter text into the "First Name" field and tab-out, then you will see an XHR in your browser Network tab. Notice that all request parameters are prefixed such as `Pluto_com_liferay_faces_demo_butterfaces_applicant_portlet_1_941024683_0_javax.faces.ViewState` except for `javax.faces.source`, `javax.faces.partial.execute`, `javax.faces.partial.render`, `javax.faces.behavior.event`, and `javax.faces.partial.ajax` because ButterFaces is not namespacing them.

But if you click on the "Show Comments" link, those same request parameters are namespaced properly by jsf.js since `h:commandLink` uses plain `f:ajax` and the rendered anchor tag's onclick attribute passes the "com.sun.faces.namingContainerId" option to `mojara.ab(...)` which ultimately passes the same option to `jsf.js.request(...)`:

```<a id="Pluto_com_liferay_faces_demo_butterfaces_applicant_portlet_1_941024683_0_:f1:j_idt28" href="#" onclick="mojarra.ab(this,event,'action',0,'Pluto_com_liferay_faces_demo_butterfaces_applicant_portlet_1_941024683_0_:f1:commentsField',{'com.sun.faces.namingContainerId':'Pluto_com_liferay_faces_demo_butterfaces_applicant_portlet_1_941024683_0_'});return false" name="Pluto_com_liferay_faces_demo_butterfaces_applicant_portlet_1_941024683_0_:f1:j_idt28">Show Comments</a>```

**Comment by ngriffin7a** [comment]
@szerhusenBC FYI, this issue is a "nice to have" for our upcoming Liferay Faces release but is not essential since we have a workaround. Would be great if you could fix it sometime in the near future though. Thanks.

**Comment by larmic** [comment]
Close because of inactivity. If this behavior is still incorrect or unwanted, please create a new issue.
