### ISSUE TITLE
ButterFaces commandLink throws JavaScript when disabling element with id containing colon character (":") 

### ISSUE THREAD

**Issue by stiemannkj1** [ButterFaces/ButterFaces#116]
This issue occurs in a portlet environment where the `UIViewRoot` implements `NamingContainer` causing ids to be prepended with `portletNamespace:`.

This bug causes the following JavaScript error in Firefox:

> Error: Syntax error, unrecognized expression: unsupported pseudo: f2

The id of the element (`f2` in this case) is taken to be a CSS pseudo class rather than another part of the whole client id (`portletNamespace:f2`).

**Comment by ngriffin7a** [comment]
@larmic Thanks so much for merging Kyle's fix. Along with #118, would it be possible for you to fix this issue soon and do a patch release? We hope to have an updated release of Liferay Faces soon with support for ButterFaces. Thanks.
