### ISSUE TITLE
Submitted value and validation input are not equal on leading whitespace

### ISSUE THREAD

**Issue by DEXRAY** [ButterFaces/ButterFaces#120]
if trim feature is active on component the submitted value and the validated value is different.

current (activ trim on component):
Form Value: "      test"
Value to Validate : "      test"
submitted value: "test"

expected (activ trim on component):
Form Value: "      test"
Value to Validate : "test"
submitted value: "test"

**Comment by larmic** [comment]
We will take a look on it.

**Comment by larmic** [comment]
comes with next release
