### ISSUE TITLE
Inputfields are not cross site scripting secured

### ISSUE THREAD

**Issue by HenneInYourFace** [ButterFaces/ButterFaces#121]
you can do cross-site scripting in Inputfields
when there is a tree-structure the source code is visible

**Comment by larmic** [comment]
Not a bug of the input fields at all. But some elements of tree components are not escaped. This should be fixed.

**Comment by larmic** [comment]
Fixed with pull request: https://github.com/ButterFaces/ButterFaces/pull/122
