### ISSUE TITLE
Invalid UIInput components highlighter that behaves like ButterFaces input components

### ISSUE THREAD

**Issue by vmuth85** [ButterFaces/ButterFaces#126]
I would appreciate a mechanism or a component that extends the standard JSF UIInput in its validation behaviour. To be more precise, imagine you have a <h:selectOneMenu> with a required="true" attribute.
In case of a validation error, the <h:selectOneMenu> doesn't look and behave like the others ButterFaces components.
To mimic the behaviour I've got two options, writing a custom PhaseListener that manipulates the DOM and make some js magic to achieve this behaviour or using the OmniFaces highligher that is doing the job: http://showcase.omnifaces.org/components/highlight
Using the OmniFaces highligher is an option for me, but it doesn't render the validation message in the way ButterFaces components do. So the look & feel of my application isn't consistent.

**Comment by larmic** [comment]
Hi @vmuth85 
this sound interesting. I will think about it and will discuss it with the other developers in january 2018

**Comment by larmic** [comment]
Close because of inactivity. If this behavior is still incorrect or unwanted, please create a new issue.
