### ISSUE TITLE
Version 3.0.0 [input component:markdown] combination from ordered and unordered List is not possible

### ISSUE THREAD

**Issue by henne1** [ButterFaces/ButterFaces#161]
when i want a List with ordered and unordered items,
then the bullet-items will interpreted as a numbered

Input:
1. first
1. second

- list

1. third

Expected: 
1. first
2. second
* list
3. third
* list

Actual:
1. first
2. second
3. list
4. third
5. list

And reverse when you start with - all followed items are bulleted

**Comment by larmic** [comment]
This does not work in preview (is a bug of http://www.codingdrama.com/bootstrap-markdown/).

But after submit and setting component to readonly everything is fine. 

I will close this...
