### ISSUE TITLE
Version 3.0.0 [input component:calendar] negative date can be submitted

### ISSUE THREAD

**Issue by henne1** [ButterFaces/ButterFaces#164]
when you go back in the calender till you can choose negative years and 
when you submit the negative date 
then the value get the negative date

![15-02-2018 11-05-22](https://user-images.githubusercontent.com/22236097/36251082-2803ce56-1240-11e8-8087-b3b39fcfb842.png)

**Comment by larmic** [comment]
I cannot not reproduce it with latest version. please check snapshot
