### ISSUE TITLE
Image Icon is not working

### ISSUE THREAD

**Issue by burakuluu** [ButterFaces/ButterFaces#178]
Image icon doesn't seem working even if I set the path.

Here's the how my folder structure looks like;
![image](https://user-images.githubusercontent.com/25999821/36732119-db5eddfa-1bdd-11e8-9bfa-cdbf2649fa7b.png)

And how my code looks like;
![image](https://user-images.githubusercontent.com/25999821/36732195-14d8a49e-1bde-11e8-9aa8-680003a9f5c6.png)

What did I do wrong that image doesn't appear?

Thanks.

**Comment by larmic** [comment]
Try to put your images to `src/main/webapp/resources/images/`

This works for ButterFaces showcase: https://github.com/ButterFaces/ButterFaces/tree/master/showcase/src/main/webapp/resources/images

**Comment by burakuluu** [comment]
That works! Perfect man! Thank you so much! @larmic

**Comment by larmic** [comment]
You are welcome.

closed :)
