### ISSUE TITLE
Showcase - tree - Display of search field

### ISSUE THREAD

**Issue by masebast** [ButterFaces/ButterFaces#181]
The search input field is very unobtrusive; almost as if the designers wanted to conceal it amongst all the other information on the page. I reckon that users who do not visit the page regularly will often miss the opportunity to search the tree.

I'd recommend to put a box around the search field and stick a label or symbol (e.g. looking glass) to it.

**Comment by larmic** [comment]
The used component brings this design with. We could adjust it, but I can not think of anything better.
I would also be reluctant to adapt, as this can always lead to errors when updating the component (which we do regularly).
However, any user can customize the design themselves with the help of css.
