### ISSUE TITLE
Showcase - calendar - component tooltip blocks right arrow in datepicker

### ISSUE THREAD

**Issue by masebast** [ButterFaces/ButterFaces#184]
When the calendar icon is clicked a datepicker and a tooltip appear at the same time. The tooltip obscures the right arrow in the upper right corner of the datepicker. When the user clicks into the tooltip at the place where the right arrow is obscured the datepicker disappears.
There is a workaround: at the left border of the tooltip some pixels of the focus shadow are displayed. Klicking in that area will count as clicking the arrow.

**Comment by larmic** [comment]
Tooltip position changed from bottom (default) to top. Comes with next showcase deployment.
