### ISSUE TITLE
Showcase - checkBox - vertical alignment of check box

### ISSUE THREAD

**Issue by masebast** [ButterFaces/ButterFaces#186]
The bottom line of the check box is a few pixels higher than the baseline of its associated text. This gives an unclean impression of the component. 
If the switch element is rendered instead of the box the aligment is perfect.

**Comment by larmic** [comment]
We are using flex layout. In Chome everything seems to be fine. This bug is browser dependent. Maybe this will be fixed by upcoming browser release.
