### ISSUE TITLE
Showcase - markdown - \n not working in placeholder

### ISSUE THREAD

**Issue by masebast** [ButterFaces/ButterFaces#187]
There is a hint that mentions the option of using multiline placeholders by adding '\n'. In the showcase, however, line feed characters within the placeholder text are ignored.

**Comment by larmic** [comment]
You are right. The updated component does not support \n but two two blank spaces at the end of the line.

I will update the showcase hint

**Comment by larmic** [comment]
Comes with next showcase deployment
