### ISSUE TITLE
Input component 'number' - min/max replaces input

### ISSUE THREAD

**Issue by masebast** [ButterFaces/ButterFaces#193]
If a minimum or maximum value is specified and a higher/lower number is entered it is silently replaced with the minimum respectively maximum value. This behaviour is error prone. Subsequent operation will be based on a value the user did not intend to specify. 
I suggest that instead of silently replacing the input it should be removed and the user should be informed why his/her value was not accepted.

**Comment by larmic** [comment]
Close because of inactivity. If this behavior is still incorrect or unwanted, please create a new issue.
