### ISSUE TITLE
Input component 'tags' - attribute 'disabled' not editable in showcase

### ISSUE THREAD

**Issue by masebast** [ButterFaces/ButterFaces#201]
The checkbox 'disabled' can be selected and deselected, but this has neither an effect on the XHTML code nor on the behaviour of the input element.

**Comment by larmic** [comment]
On Chrome it seems to work. Which browser are you using?

**Comment by masebast** [comment]
I was using IE 11.0.9600. However, I could not reproduce the the behaviour right now. I guess that when playing around I encountered some side effect which depends on a very specific constellation and/or usage history. 
I suggest to close the issue. I would reopen it if I hit that specific constellation again.
