### ISSUE TITLE
Input component 'tags' - attribute 'maxtags' without user notification

### ISSUE THREAD

**Issue by masebast** [ButterFaces/ButterFaces#202]
When the user enters more tags than specified by the maxtags attribute then any additional elements are ignored and removed from the input field. However, the user is not informed about the effective maximum. There should be a warning, e.g. in form of a tooltip, as there is for input validation with other input components.

**Comment by larmic** [comment]
Close because of inactivity. If this behavior is still incorrect or unwanted, please create a new issue.
