### ISSUE TITLE
text: type constraint checking

### ISSUE THREAD

**Issue by masebast** [ButterFaces/ButterFaces#217]
I set the type of a text element to 'number' and min and max attributes to 1 and 4 respectively. Entering the value 5 followed by submit will briefly highlight the input box in red while still accepting the input value. Entering a value below the specified minimum will result in the same behaviour. 

I expected an invalid input value to be rejected as is the case with the check on string length when applying the ValidateLength attribute.

**Comment by masebast** [comment]
I used Firefox version 60.3.0.esr. I just tried with Internet Explorer version 11.09600. Again the incorrect input is accepted but this time without the brief red frame that I see with Firefox.

By the way:  I'd consider the bevaviour you described in your comment, i.e. replacing the incorrect value by a valid one, as a serious bug, too. It is as if the application said: "I don't like the value you submitted, so I'll take one I like instead." An incorrect value should neither be accepted nor replaced by a valid one.

**Comment by larmic** [comment]
@szerhusenBC what is your opinion?

**Comment by szerhusenBC** [comment]
@larmic isn't this a duplicate of #193?

**Comment by larmic** [comment]
Close because of inactivity. If this behavior is still incorrect or unwanted, please create a new issue.
