### ISSUE TITLE
b:tree TreeNodeSelectionListener.processValueChange is not called

### ISSUE THREAD

**Issue by cdipiet** [ButterFaces/ButterFaces#232]
In the showcase:
http://www.butterfaces.org/tree.jsf
when selecting a node in the tree, the TreeNodeSelectionListener.processValueChange 
in org.butterfaces.component.showcase.tree.TreeShowcase
is not called. The b:text label="Selected value" inside tree.xhtml remains empty when any node in the tree is selected.

**Comment by larmic** [comment]
Thanks, thats interesting. On my local machine everything is working fine. I will take a look on it.

**Comment by cdipiet** [comment]
Hello, just a little bit of more info, I tried the tree selection at http://www.butterfaces.org/tree.jsf with another pc, this time is a Linux machine, I tried again with both Firefox 69 and Chrome 77.0.3865.90, it is not working with both(so it seems an issue independent from os or browser). Thanks

**Comment by larmic** [comment]
I've replaces jsf.request.ajax parameter 'params' by 'butterfaces-params'. Specified parameter 'params' seems not to work correctly when using JSF 2.3 and wildfly or thorntail.

Thanks for supporting us by creating a bug ticket! Feel free to found some more bugs. :) 

I will build a new final butterfaces version within the next week.
