### ISSUE TITLE
Showcase - table - Toolbar button "Column options" not working

### ISSUE THREAD

**Issue by cdipiet** [ButterFaces/ButterFaces#235]
Hello, the showcase http://www.butterfaces.org/table.jsf
toolbar button "Column options" in not working, unchecking any colum it still remain visibile.
Also moving a column to left or right is not working.
(tablemodel is enabled)

**Comment by larmic** [comment]
Hi, this seems to be the same issue as #232. Something is wrong when using JSF 2.3 and ajax parameters.

**Comment by larmic** [comment]
I've replaced jsf.request.ajax parameter 'params' by 'butterfaces-params'. Specified parameter 'params' seems not to work correctly when using JSF 2.3 and wildfly or thorntail.

Thanks for supporting us by creating a bug ticket! Feel free to found some more bugs. :) 

I will build a new final butterfaces version within the next week.
