### ISSUE TITLE
Input component number - clicking on up/down arrow reset to min when value has been initialized with a bean

### ISSUE THREAD

**Issue by cdipiet** [ButterFaces/ButterFaces#239]
When the input component number: 
has been initialized from a backing been with a value. Clicking on up/down arrows reset it to min value.
Example from the showcase: http://www.butterfaces.org/number.jsf
1. fill the component with value '5'
2. press submit -> now the component take its value from a bean
3. click up arrow -> component value is reset to 0 (or min if it has been set)

The same happen when the component value is initialized from a backing bean.

**Comment by larmic** [comment]
I will take a look on it.
