### ISSUE TITLE
Download Jars

### ISSUE THREAD

**Issue by ghaseminya** [ButterFaces/ButterFaces#274]
Hi larmic
Thanks you for a complete jsf framework development.
Can download jar of butterfaces? I can't found it in mvn  repository.
This [link](http://search.maven.org/remotecontent?filepath=de/larmic/butterfaces/components/3.3.3/components-3.3.3.jar) not work.

**Comment by larmic** [comment]
Hi,

here you can find our latest release: https://repo1.maven.org/maven2/org/butterfaces/components/3.3.3/

Here you can find the first steps: https://butterfaces.github.io/getting_started.html

**Comment by ghaseminya** [comment]
Thanks
