### ISSUE TITLE
Icons font awesome

### ISSUE THREAD

**Issue by dguna** [ButterFaces/ButterFaces#279]
Butter faces 3.4 does not come with font awesome. Is there optimal way to use it with butterfaces? Thanks

**Comment by larmic** [comment]
ButterFaces comes with https://www.npmjs.com/package/glyphicons-only-bootstrap.
With Bootstrap 5 we will change it to https://icons.getbootstrap.com/.

If you want to use font awesome you have to import it by yourself.

[Here you can find an example](http://butterfaces.org/calendar.jsf). Switch glyphicon to font awesome icons.

**Comment by larmic** [comment]
Hi @dguna,

I will close this issue. Feel free to ask another question.

**Comment by dguna** [comment]
thnaks very much. Please let me know if can participate this development effort. I am migratinting from bootsfaces.
