### ISSUE TITLE
Integration with primefaces

### ISSUE THREAD

**Issue by dguna** [ButterFaces/ButterFaces#280]
I have lot of css problems with some primefaces components like "growl". Is there someting equivalent in butterfaces.

Second question in the table there is a id in the column component is causing some problems if you don't use table model

**Comment by larmic** [comment]
Hi @dguna,

I'm sorry, but @szerhusenBC  and I currently have little time for primefaces integration. We haven't a growl component. I will discuss this with @szerhusenBC.

I will take a look on the table issue.

**Comment by larmic** [comment]
Close because of inactivity. If this behavior is still incorrect or unwanted, please create a new issue.
