### ISSUE TITLE
Available characters for a b:textArea are displayed in German

### ISSUE THREAD

**Issue by jepsar** [ButterFaces/ButterFaces#36]
.. while the rest of the [view](http://www.butterfaces.org/butterfaces-showcase/textarea.jsf) is in English

**Comment by larmic** [comment]
What kind of available characters do you mean?

**Comment by jepsar** [comment]
"9 von 10 Zeichen" (bottom right)

**Comment by larmic** [comment]
Ah ok, you are using the maxLength attribute. Thanks, we will fix it.

**Comment by larmic** [comment]
2.1.2 is moving to maven central repository.

New default is '{0} of {1} characters'. You can add a web.xml context parameter **org.butterfaces.maxLengthText** to change it.

**Comment by larmic** [comment]
Configuration has been changed. 

Closed.
