### ISSUE TITLE
b:maskedText has no support for pattern options

### ISSUE THREAD

**Issue by DEXRAY** [ButterFaces/ButterFaces#50]
maskedText contains no possibility to change pattern options. 

example : 
.inputmask("mm/yyyy", {yearrange: {minyear: 2000, maxyear: 2999}})

the parameter maskedInput in maskedText supports only the pattern "mm/yyyy". There is no possibility to Change maxyear from 2099 to 2999

**Comment by larmic** [comment]
With 2.1.4 ButterFaces will support maskedInput="'mm/yyyy', {yearrange: {minyear: 2000, maxyear: 2999}}"
