### ISSUE TITLE
labels' for attribute should reference full client ID

### ISSUE THREAD

**Issue by fkaempfer** [ButterFaces/ButterFaces#51]
Usually when you click on the label for any input component, the corresponding component gets focused. For example when clicking on the label for an inputText component, the expected result is that you can start typing immediately, which works when the for attribute is set correctly.

In ButterFaces showcase I saw that currently only the ID part of the component client id is referenced, not the full client id. Probably it's easy to fix, or is it already?

EDIT: I just realized that the input in the show case does not even have an ID attribute set (only the name), so it's actually more complicated..

**Comment by larmic** [comment]
You are right. We could add an ID attribute on the corresponding input.
I will fix it in the next version.

**Comment by fkaempfer** [comment]
Awesome, thanks.

**Comment by larmic** [comment]
I've released 2.1.5 and nearly every components supports this feature now.

Except b:treeBox and b:tags does not work because trivial components does not support this feature. I will create an issue for this framework.

This issue stays open until trivial components is fixed.

**Comment by larmic** [comment]
Bug in trivial components: https://github.com/trivial-components/trivial-components/issues/38

**Comment by fkaempfer** [comment]
Looks great, thanks! It increases the usability of forms (a little bit).

**Comment by larmic** [comment]
Close because of inactivity.
