### ISSUE TITLE
I would appreciate paging for the table-component

### ISSUE THREAD

**Issue by 7ibe** [ButterFaces/ButterFaces#53]
If you have many datasets which should be shown in the table-component, then you will have long scrollbar.

A paging mechanism would help.

**Comment by prostagma** [comment]
+1

**Comment by larmic** [comment]
I'm not sure about the design of such a component. 

Todo: 
* Think about it
* implement a table values model
* implement a proposal

**Comment by larmic** [comment]
Close because of inactivity.
