### ISSUE TITLE
Integration with BootsFaces ERROR! 

### ISSUE THREAD

**Issue by cooper-lyt** [ButterFaces/ButterFaces#54]
Integration butterFaces 2.1.4 , all BootsFaces's DropDown menu is invalid！

[bootsFaces issues](https://github.com/TheCoder4eu/BootsFaces-OSP/issues/414)

maven:

`<dependency><groupId>de.larmic.butterfaces</groupId> <artifactId>components</artifactId> <version>2.1.4</version> </dependency>
`

web.xml
`<context-param> <param-name>javax.faces.PROJECT_STAGE</param-name> <param-value>Production</param-value> </context-param>`

but, if set javax.faces.PROJECT_STAGE to Development will be ok! 
i view the html source , if set javax.faces.PROJECT_STAGE to Production then add include a script:
`<script type="text/javascript" src="/RestaurantERP_SNAPSHOT/javax.faces.resource/butterfaces-all-with-jquery-and-bootstrap-bundle.min.js.xhtml?ln=butterfaces-dist-bundle-js">`

**Comment by larmic** [comment]
Which version of ButterFaces and BootsFaces do you use?

Are you using 
´´´
<context-param>
    <param-name>net.bootsfaces.get_jquery_from_cdn</param-name>
    <param-value>false</param-value>
</context-param>
```

**Comment by cooper-lyt** [comment]
`    <dependency>
      <groupId>net.bootsfaces</groupId>
      <artifactId>bootsfaces</artifactId>
      <version>0.8.6</version>
      <scope>compile</scope>
    </dependency>
`
`  <dependency>
      <groupId>de.larmic.butterfaces</groupId>
      <artifactId>components</artifactId>
      <version>2.1.4</version>
    </dependency>`

context param `net.bootsfaces.get_jquery_from_cdn` add or remove , is same error!

**Comment by larmic** [comment]
in BootsFaces 0.8.6 net.bootsfaces.get_jquery_from_cdn does not seems to work anymore. This creates an issue using jQuery plugins.

Maybe should be fixed in BootsFaces or param has been renamed?

**Comment by larmic** [comment]
I'm not sure if BootsFaces will be fix this. I will add a fix in ButterFaces to remove BootsFaces jQuery from head.

**Comment by larmic** [comment]
As described in https://github.com/TheCoder4eu/BootsFaces-OSP/issues/414 parameter net.bootsfaces.get_jquery_from_cdn has set to true instead to false. This changed in some version of BootsFaces.

Bug with dropdown has been fixed in BootsFaces.
