### ISSUE TITLE
Placeholder with new lines

### ISSUE THREAD

**Issue by vmuth85** [ButterFaces/ButterFaces#56]
Carriage returns or new lines are not supported by the placeholder attribute specification,
but it is a very common requirement to include sample content that may need new lines.

I've seen a very simple and elegant way of getting it done on:
https://bendechrai.com/2013/04/03/textarea-placeholder-with-new-lines/

The code works just fine with the ButterFaces textArea, all you have to do is just replacing the
$(this).attr('value', ''); by 
$(this).val(''); 
and 
$(this).attr('value', $(this).attr('data-placeholder'));
by
$(this).val($(this).attr('data-placeholder'));

So I guess an integration in the  ButterFaces textArea or other components supporting the placeholder attribute won't be that difficult?

**Comment by larmic** [comment]
This is an interesting feature. 

I will try to implement this in the next version.

**Comment by larmic** [comment]
After a short review I see some problems using https://bendechrai.com/2013/04/03/textarea-placeholder-with-new-lines/

- setting placeholder value on a textarea will transport it on form submit
- if the user want to use the placeholder value to submit it does not work
- default behavior of placeholder is not correctly supported (placeholder is hidden when components is focused)

A better way is to replace placeholder attribute by javascript:
```
$(document.getElementById('output:outputComponent:textArea:inner')).attr('placeholder', $(document.getElementById('output:outputComponent:textArea:inner')).attr('placeholder').replace(/\\n/g, '\n'));
```

**Comment by larmic** [comment]
ButterFaces 2.1.7 is released and should be available in maven central in a few minutes.

**Comment by vmuth85** [comment]
Wow, incredible, I have never seen such a rapid implementation! Thank you!

**Comment by larmic** [comment]
You are welcome.
