### ISSUE TITLE
butter treebox invokes toSting method in template

### ISSUE THREAD

**Issue by DEXRAY** [ButterFaces/ButterFaces#67]
The butterfaces treeBox invokes toString on Pojos, This isn't always necessary when name template is used. If the toString method return multi line output this can cause ui errors.

**Comment by larmic** [comment]
I'm thinking about it. It does not seems to be a defect.

**Comment by larmic** [comment]
Ok, it seems we should escape toString() for html usage

**Comment by larmic** [comment]
Fixed and comes with 2.1.11
