### ISSUE TITLE
Add date range picker

### ISSUE THREAD

**Issue by larmic** [ButterFaces/ButterFaces#71]
https://github.com/eternicode/bootstrap-datepicker

is supporting it. switching to this plugin?

**Comment by szerhusenBC** [comment]
Hmm, this plugin looks nice. Do you want to replace the actual date input component as well?

**Comment by larmic** [comment]
I don't know. This plugin does not have time support

**Comment by szerhusenBC** [comment]
Hmm, or we try to build our own range picker with a component combining two of our existing date pickers ...

**Comment by larmic** [comment]
This feature will not be implemented for the next time.
