### ISSUE TITLE
issue with confirmkeys in tags component

### ISSUE THREAD

**Issue by ybendek** [ButterFaces/ButterFaces#76]
If you use the "comfirmkeys" with this component for example ',' character, then each tag allows the use of "spaces". However after you submit the data and use the same component to display the tags collection for example with "readonly" attribute, the component display tags using a combination between spaces and the confirmkeys value. This could be reproduced even with the demo site.

**Comment by larmic** [comment]
Hi @ybendek,

this seems to be a bug. Thanks for reporting it. I will fix it.

**Comment by ybendek** [comment]
Awesome, thank you... do you have an estimate when this could be solved?

**Comment by larmic** [comment]
Hi,

I've released 2.1.14 a few minutes ago. It should be available in maven central within the next hours.

Please let me know if you have other issues with this component (or other components :))

**Comment by ybendek** [comment]
awesome...it works like a charm
