### ISSUE TITLE
Integration with Primefaces

### ISSUE THREAD

**Issue by ybendek** [ButterFaces/ButterFaces#77]
Hello

I'm trying to use some components provided for ButterFaces (mainly tags component), however the main framework I use is Primefaces (V6.0). Starting to work with both I try the workaround provided for you to integrate both, however disabling the jquery provided by Primefaces could produce some bugs from the primefaces site.

Trying to understand the problem I found that with the following parameters it works(at least what I need, the tags component):
javax.faces.PROJECT_STAGE=**Development**
org.butterfaces.provideJQuery=false
org.butterfaces.provideBootstrap=false
org.butterfaces.integration.primefaces.disableJQuery=false

However when I change the parameter javax.faces.PROJECT_STAGE=**Production** then I have warning from the browser console and butterfaces components start to fail.

Why is so different? Why cannot be included the butterfaces components in the same way for both modes?

Thanks in advance for your help.

**Comment by larmic** [comment]
Hi,

are you using Spring Boot? Can you post the warning?

The main problem is that PrimeFaces and ButterFaces both comes with jQuery and one of them should be disabled.

I will take a look on your problem.

**Comment by ybendek** [comment]
Hi,

Not I'm not using Spring Boot, this is the warning I have in chrome console
`butterfaces-all-bundle.min.js.tlib?ln=butterfaces-dist-bundle-js:8 Uncaught bootstrap-datetimepicker requires jQuery to be loaded first(anonymous function) @ butterfaces-all-bundle.min.js.tlib?ln=butterfaces-dist-bundle-js:8(anonymous function) @ butterfaces-all-bundle.min.js.tlib?ln=butterfaces-dist-bundle-js:8
VM126:9 Uncaught ReferenceError: TrivialComponents is not defined(…)(anonymous function) @ VM126:9i @ jquery.js.tlib?ln=primefaces&v=6.0:25add @ jquery.js.tlib?ln=primefaces&v=6.0:25bH.fn.ready @ jquery.js.tlib?ln=primefaces&v=6.0:25bH.fn.init @ jquery.js.tlib?ln=primefaces&v=6.0:25bH @ jquery.js.tlib?ln=primefaces&v=6.0:14(anonymous function) @ VM126:1(anonymous function)`


This is the order of resources loaded when it is in PRODUCTION

.....
- /templateLib-web/javax.faces.resource/theme.css.tlib?ln=primefaces-ultima-blue
- /templateLib-web/javax.faces.resource/fa/font-awesome.css.tlib?ln=primefaces&amp;v=6.0
- /templateLib-web/javax.faces.resource/dist-butterfaces-only.min.css.tlib?ln=butterfaces-dist-css
- /templateLib-web/javax.faces.resource/butterfaces-all-bundle.min.js.tlib?ln=butterfaces-dist-bundle-js
- /templateLib-web/javax.faces.resource/jquery/jquery.js.tlib?ln=primefaces&amp;v=6.0
- /templateLib-web/javax.faces.resource/jquery/jquery-plugins.js.tlib?ln=primefaces&amp;v=6.0
- /templateLib-web/javax.faces.resource/mfb.css.tlib?ln=fab
- /templateLib-web/javax.faces.resource/components.css.tlib?ln=primefaces&amp;v=6.0
- /templateLib-web/javax.faces.resource/core.js.tlib?ln=primefaces&amp;v=6.0
- /templateLib-web/javax.faces.resource/components.js.tlib?ln=primefaces&amp;v=6.0
- /templateLib-web/javax.faces.resource/touch/touchswipe.js.tlib?ln=primefaces&amp;v=6.0
- /templateLib-web/javax.faces.resource/css/nanoscroller.css.tlib?ln=ultima-layout
- /templateLib-web/javax.faces.resource/css/animate.css.tlib?ln=ultima-layout
- /templateLib-web/javax.faces.resource/css/ripple.css.tlib?ln=ultima-layout.......



And this is in Development
.....
- /templateLib-web/javax.faces.resource/theme.css.tlib?ln=primefaces-ultima-blue
- /templateLib-web/javax.faces.resource/fa/font-awesome.css.tlib?ln=primefaces&amp;v=6.0
- /templateLib-web/javax.faces.resource/mfb.css.tlib?ln=fab
- /templateLib-web/javax.faces.resource/components.css.tlib?ln=primefaces&amp;v=6.0
- /templateLib-web/javax.faces.resource/jquery/jquery.js.tlib?ln=primefaces&amp;v=6.0
- /templateLib-web/javax.faces.resource/core.js.tlib?ln=primefaces&amp;v=6.0
- /templateLib-web/javax.faces.resource/components.js.tlib?ln=primefaces&amp;v=6.0
- /templateLib-web/javax.faces.resource/jquery/jquery-plugins.js.tlib?ln=primefaces&amp;v=6.0
- /templateLib-web/javax.faces.resource/touch/touchswipe.js.tlib?ln=primefaces&amp;v=6.0
- /templateLib-web/javax.faces.resource/butterfaces-default.css.tlib?ln=butterfaces-dist-css"
- /templateLib-web/javax.faces.resource/butterfaces-tags.css.tlib?ln=butterfaces-dist-css"
- /templateLib-web/javax.faces.resource/butterfaces-trivial-components.css.tlib?ln=butterfaces-dist-css
- /templateLib-web/javax.faces.resource/mustache.min.js.tlib?ln=butterfaces-external
- /templateLib-web/javax.faces.resource/jquery.position.min.js.tlib?ln=butterfaces-external
- /templateLib-web/javax.faces.resource/trivial-components.min.css.tlib?ln=butterfaces-external
- /templateLib-web/javax.faces.resource/trivial-components-bootstrap.min.css.tlib?ln=butterfaces-external
- /templateLib-web/javax.faces.resource/trivial-components.min.js.tlib?ln=butterfaces-external
- /templateLib-web/javax.faces.resource/butterfaces-tags.jquery.js.tlib?ln=butterfaces-js
- /templateLib-web/javax.faces.resource/css/nanoscroller.css.tlib?ln=ultima-layout
- /templateLib-web/javax.faces.resource/css/animate.css.tlib?ln=ultima-layout
- /templateLib-web/javax.faces.resource/css/ripple.css.tlib?ln=ultima-layout
.....

The big question is why is so different just changing the javax.faces.PROJECT_STAGE parameter?, could not be the same?

**Comment by larmic** [comment]
Ok, it seems to be an issue with jquery resource ordering. I will take a look on our resource ordering algorithm.

**Comment by larmic** [comment]
Ok,

you are using PrimeFaces jQuery instead of ButterFaces jQuery. In our demo https://github.com/ButterFaces/primefaces-integration we are using ButterFaces jQuery and disable PrimeFaces jQuery.

This works for me
`javax.faces.PROJECT_STAGE=PRODUCTION
org.butterfaces.provideJQuery=true
org.butterfaces.provideBootstrap=true
org.butterfaces.integration.primefaces.disableJQuery=true`

If you want to disable jQuery in ButterFaces and want to use your own (or PrimeFaces) version you have to implement a custom SystemEventListener (described in https://github.com/ButterFaces/primefaces-integration) and order jQuery in front of ButterFaces and PrimeFaces.

Is this helpful?

**Comment by ybendek** [comment]
Hmm... 

Apparently I found another workaround, Reviewing the source code and trying to understand the difference between PRODUCTION and DEVELOPMENT stage I found something interesting in the HandleResourceListener class.

In the following lines:
// Production mode and compressed
        if (useCompressedResources && context.getApplication().getProjectStage() == ProjectStage.Production) {
            handleCompressedResources(context, provideJQuery, provideBootstrap, resources, source);
        } else {
            handleConfigurableResources(context, provideJQuery, provideBootstrap, resources, source);
        }....


If you use the following configuration it works :
```
org.butterfaces.provideJQuery=false
org.butterfaces.provideBootstrap=false
org.butterfaces.integration.primefaces.disableJQuery=false
org.butterfaces.useCompressedResources=false
```
and resouces are rendered in correct order 
```
.../javax.faces.resource/theme.css.tlib?ln=primefaces-ultima-blue
.../javax.faces.resource/fa/font-awesome.css.tlib?ln=primefaces&amp;v=6.0
.../javax.faces.resource/mfb.css.tlib?ln=fab
.../javax.faces.resource/components.css.tlib?ln=primefaces&amp;v=6.0
.../javax.faces.resource/jquery/jquery.js.tlib?ln=primefaces&amp;v=6.0
.../javax.faces.resource/core.js.tlib?ln=primefaces&amp;v=6.0
.../javax.faces.resource/components.js.tlib?ln=primefaces&amp;v=6.0
.../javax.faces.resource/jquery/jquery-plugins.js.tlib?ln=primefaces&amp;v=6.0
.../javax.faces.resource/touch/touchswipe.js.tlib?ln=primefaces&amp;v=6.0
.../javax.faces.resource/butterfaces-default.css.tlib?ln=butterfaces-dist-css
.../javax.faces.resource/butterfaces-tags.css.tlib?ln=butterfaces-dist-css
.../javax.faces.resource/butterfaces-trivial-components.css.tlib?ln=butterfaces-dist-css
.../javax.faces.resource/mustache.min.js.tlib?ln=butterfaces-external
.../javax.faces.resource/jquery.position.min.js.tlib?ln=butterfaces-external
.../javax.faces.resource/trivial-components.min.css.tlib?ln=butterfaces-external
.../javax.faces.resource/trivial-components-bootstrap.min.css.tlib?ln=butterfaces-external
.../javax.faces.resource/trivial-components.min.js.tlib?ln=butterfaces-external
.../javax.faces.resource/butterfaces-tags.jquery.js.tlib?ln=butterfaces-js
.../javax.faces.resource/css/nanoscroller.css.tlib?ln=ultima-layout
.../javax.faces.resource/css/animate.css.tlib?ln=ultima-layout
.../javax.faces.resource/css/ripple.css.tlib?ln=ultima-layout

```

Then I guess the problem is with the handleCompressedResources method and the way as it generates the resources.

**Comment by larmic** [comment]
In case of multiple jQuery resources we have to order it in a correct way. Some frameworks (like ButterFaces) comes with bundles resources and some not. 

The default way is to use ButterFaces jQuery and disable other resources. I think it is correct to deliver a bundles resource if project stage is production.

Can you use jQuery from ButterFaces? Otherwise you have to create your own HandleResourceListener and order jQuery by yourself.

**Comment by ybendek** [comment]
yes you are right, but i'm worried about to change the jQuery used by Primefaces, some components or behaviors could fail with an updated jQuery, they use an old version. :S

**Comment by larmic** [comment]
Ok, I will close this. :)
