### ISSUE TITLE
new component Floating Buttons

### ISSUE THREAD

**Issue by ybendek** [ButterFaces/ButterFaces#79]
Could be nice to add a similar component like the Floating Buttons used in Google Material

https://material.google.com/components/buttons-floating-action-button.html#buttons-floating-action-button-behavior

I have been using this one https://github.com/nobitagit/material-floating-button and integrate it manually with my JSF app... could be great to have something working with JSF components like buttons or menus.

**Comment by larmic** [comment]
hi @ybendek,

I will discuss this with the other developers. This could be a nice gimmick.

**Comment by larmic** [comment]
@ybendek this could be a nice feature but I don't have any time to implement this within the next months. 

This issue is on hold.

**Comment by larmic** [comment]
Never heard of you again. I will close this ticket. Feel free to create a new ticket or send us a pull request.
