### ISSUE TITLE
Tags and autocomplete

### ISSUE THREAD

**Issue by ybendek** [ButterFaces/ButterFaces#80]
Hello, I found this tag contains a boolean attribute called "autocomplete", but I cant find examples with this feature, is this available? could I use an autocomplete features to include "known" tags?

**Comment by larmic** [comment]
Hi @ybendek,

auto complete is not ready for production. Issue #47 should handle it. Maybe I will implement this feature in the next weeks.

**Comment by ybendek** [comment]
Awesome, thank you

**Comment by larmic** [comment]
Ok, then I will close this issue.
