### ISSUE TITLE
Add new component for input with unit selection

### ISSUE THREAD

**Issue by szerhusenBC** [ButterFaces/ButterFaces#91]
We need a component with an input field and a drop down like selection for units (see screenshot).

**Comment by szerhusenBC** [comment]
![bildschirmfoto 2016-12-14 um 11 11 03](https://cloud.githubusercontent.com/assets/8706855/21178111/564e53ce-c1ee-11e6-977f-aec6161f565c.png)

**Comment by larmic** [comment]
What's up with using a b:text and right facet?

**Comment by szerhusenBC** [comment]
@larmic Didn't see your objection ;)

We will check that tomorrow ...

**Comment by larmic** [comment]
Close? And remove branch?

**Comment by szerhusenBC** [comment]
Ticket can be closed, but the branch not yet. We can reuse the language support from it.
