### ISSUE TITLE
Tooltip: Does not escape colons in the for attribute

### ISSUE THREAD

**Issue by vmuth85** [ButterFaces/ButterFaces#96]
The generated java script for the tooltip doesn't escape the unique identifier defined by the for attribute.
Most of the ButterFaces components are escaping the unique identifier by using the following code:

> jQuery(document.getElementById('output:outputComponent:text'))

While the tooltip generates this one:

> jQuery('output:outputComponent:text')

I'm not sure whether this behavior is intended. Although the second approach gives you the ability to pass through any selector you want to and not just an id, you still have to insure, that your selector doesn't contain any colons.
So if the tooltip works as designed, could you just extend the behaviour in order to replace all colons?

**Comment by larmic** [comment]
Hi,

this seems to be a bug. All ButterFaces components should escape the unique identifier. 

I will fix this.

**Comment by larmic** [comment]
I have to adjust my answer:

if you use an embedded tooltip like _<b:text><:b:tooltip /></b:text>_ everything works as intended.

If you use <b:tooltip /> for another component (maybe just a simple html component) our tooltip components finds the corresponding component by a jQuery selector. If we escape all colons other selector (:prev, :next, :last etc...) will not work anymore. 

So this does not seems to be bug.

Do you have a simple example to show what your problem is?

**Comment by vmuth85** [comment]
I've implemented a custom UIComponent **GenericElement**, this component is able to represent any HTML element. I use it in conjunction with repetitions so I don't have to blew up the DOM to have a wrapper with an uniqe identifier to run an ajax update against. The following code is a snippet of my
Composite Component that is use in a **<c:forEach>** repetition.

```
<ct:genericElement id="deviceIcon" elementName="i" styleClass="material-icons cursor-pointer">
                    #{cc.attrs.deviceIcon}
</ct:genericElement>
<b:tooltip for="##{cc.clientId}\\\\:deviceIcon" trigger="hover" viewport="body" placement="right"
                 title="#{cc.attrs.device.deviceName}" >
         <div><h:outputLabel value="#{msgs['deviceInfoRow.tooltip.os']} "/>#{cc.attrs.device.os}</div>
         <div><h:outputLabel value="#{msgs['deviceInfoRow.tooltip.ip']} "/>#{cc.attrs.device.ip}</div>
         <div><h:outputLabel value="#{msgs['deviceInfoRow.tooltip.extIp']} #{cc.attrs.device.extIp}>/div>
</b:tooltip>
```
The generated HTML:

```
<i class="material-icons cursor-pointer" id="j_idt40:deviceIcon" data-original-title="" title="">
        desktop_windows
</i>
```


I am using my custom component, therefore I cannot wrap the ButterFaces tooltip into it.
It's not a big deal for me to escape the colons, but I thought it would be handy to a void writing such boilerplate code. Depending on the component depth the repalacement will become very ugly for instance: 

> bodyForm:widgets:partnerList:j_idt751_row_6

There I would have to do some more stuff like using JSTL functions fn:replace() or event writing a java method.

**Comment by larmic** [comment]
You can use instead a custom style class on your component. Did you try this:
```java
<ct:genericElement id="deviceIcon" elementName="i" styleClass="material-icons cursor-pointer custom-style-class">
                    #{cc.attrs.deviceIcon}
</ct:genericElement>
<b:tooltip for=".custom-style-class" trigger="hover" viewport="body" placement="right"
                 title="#{cc.attrs.device.deviceName}" >
         <div><h:outputLabel value="#{msgs['deviceInfoRow.tooltip.os']} "/>#{cc.attrs.device.os}</div>
         <div><h:outputLabel value="#{msgs['deviceInfoRow.tooltip.ip']} "/>#{cc.attrs.device.ip}</div>
         <div><h:outputLabel value="#{msgs['deviceInfoRow.tooltip.extIp']} #{cc.attrs.device.extIp}>/div>
</b:tooltip>
```

**Comment by vmuth85** [comment]
Thanks! This is an option, it has not occurred to me .)

**Comment by larmic** [comment]
You're welcome. -> closed
