### ISSUE TITLE
Error with a character in b:tags component

### ISSUE THREAD

**Issue by ybendek** [ButterFaces/ButterFaces#97]
Hello Guys

I'm using the b:tags component and I found a problem when I try to introduce a text with the character '  for example "other's perspective" if I use "others perspective" instead it works, even with the demo(http://www.butterfaces.org/butterfaces-showcase/tags.jsf) page fails with a message in the log "Uncaught SyntaxError: Unexpected identifier" after you submit the form

**Comment by larmic** [comment]
Oh,

thank you for finding this bug. We will fix it the next time!

Yours Lars

**Comment by ybendek** [comment]
Do you have a timeframe estimation of when the new release will be ready?

**Comment by larmic** [comment]
Hi @ybendek 
I've released 2.1.19 with this fix. It will be available in Maven central within the next hours.

**Comment by ybendek** [comment]
Awesome... thank you so much
